// resources/js/components/icons/index.js

export { default as IconHome } from './IconHome.vue'
export { default as IconSearch } from './IconSearch.vue'
export { default as IconUser } from './IconUser.vue'
export { default as IconLogin } from './IconLogin.vue'
export { default as IconLogout } from './IconLogout.vue'
export { default as IconClass } from './IconClass.vue'
export { default as IconThing } from './IconThing.vue'
export { default as IconLink } from './IconLink.vue'
export { default as IconPrivate } from './IconPrivate.vue'
export { default as IconChevronUp } from './IconChevronUp.vue'
export { default as IconChevronDown } from './IconChevronDown.vue'
export { default as IconClose } from './IconClose.vue'
export { default as IconAdd } from './IconAdd.vue'
export { default as IconEdit } from './IconEdit.vue'
export { default as IconDelete } from './IconDelete.vue'
export { default as IconSave } from './IconSave.vue'
export { default as IconTree } from './IconTree.vue'
export { default as IconGraph } from './IconGraph.vue'
export { default as IconCheck } from './IconCheck.vue'
