// resources/js/localDb/seeder.js
//
// Seeds the local IndexedDB with bootstrap objects.
// Single source of truth: resources/js/localDb/system-objects.json (the
// standard export generated by `php artisan factology:export-system-objects`).
//
// Bootstrap objects are infrastructure records referenced by the code
// (e.g. UUID::ANYTHING, UUID::USER). They are NOT user data.

import systemObjects from './system-objects.json';
import { UUID } from '../constants/uuid';
import { getDb, SYNC_STATUS } from './index';

/**
 * Seed the local DB with bootstrap system objects.
 * Runs only once per DB lifetime (checks for UUID::ANYTHING).
 */
export async function seedLocalDb() {
    const db = getDb();

    // Check if already seeded
    const everything = await db.objects.get(UUID.EVERYTHING);
    if (everything) {
        return; // Already seeded
    }

    console.log('[Seeder] Seeding bootstrap objects...');

    // ── Bootstrap things (from the standard system-objects export) ──
    const things = systemObjects.data.things || [];

    for (const t of things) {
        await db.objects.put({
            thing_id: t.thing_id,
            name: t.name,
            type: t.type,
            description: t.description || null,
            start: t.start ?? null,
            end: t.end ?? null,
            public: t.public ? 1 : 0,
            owner: t.owner,
            data: t.data ?? null,
            _syncStatus: SYNC_STATUS.SYNCED,
            _localRevision: 0,
            _serverRevision: 0,
            _serverId: null,
            _createdAt: Date.now(),
            _updatedAt: Date.now(),
        });
    }

    // ── Bootstrap links (class hierarchy edges, stable link_uuid ids) ──
    const links = systemObjects.data.links || [];

    for (const l of links) {
        await db.links.put({
            link_id: `seed-${l.link_uuid}`,
            translation: l.translation || null,
            one_thing_id: l.one_thing_id,
            link_type_id: l.link_type_id,
            other_thing_id: l.other_thing_id,
            public: l.public ? 1 : 0,
            _syncStatus: SYNC_STATUS.SYNCED,
            _localRevision: 0,
            _serverRevision: 0,
            _serverId: null,
        });
    }

    // ── Demo data (for standalone offline experience, NOT in the export) ──
    const demoObjects = [
        {
            thing_id: 'a0000000-0000-0000-0000-000000000001',
            name: 'Welcome to Factology',
            type: UUID.G_THING,
            description: 'This is a demo object stored locally on your device. Everything works offline!',
            public: 1,
        },
        {
            thing_id: 'a0000000-0000-0000-0000-000000000002',
            name: 'Offline Note',
            type: UUID.G_THING,
            description: 'Objects you create are stored locally by default.',
            public: 0,
        },
        {
            thing_id: 'a0000000-0000-0000-0000-000000000003',
            name: 'Try Editing Me',
            type: UUID.G_THING,
            description: 'Tap the edit button to change this object.',
            public: 1,
        },
    ];

    for (const obj of demoObjects) {
        await db.objects.put({
            thing_id: obj.thing_id,
            name: obj.name,
            type: obj.type,
            description: obj.description || null,
            start: null,
            end: null,
            public: obj.public ?? 1,
            owner: UUID.VICTOR_FOKIN,
            data: null,
            _syncStatus: SYNC_STATUS.LOCAL_ONLY,
            _localRevision: 1,
            _serverRevision: 0,
            _serverId: null,
            _createdAt: Date.now(),
            _updatedAt: Date.now(),
        });

        // Link demo objects to "Something" class
        await db.links.put({
            link_id: `seed-class-${obj.thing_id}`,
            translation: `"${obj.name}" is of class "Something"`,
            one_thing_id: obj.thing_id,
            link_type_id: UUID.LINK_TO_CLASS,
            other_thing_id: UUID.SOMETHING,
            public: 1,
            _syncStatus: SYNC_STATUS.LOCAL_ONLY,
            _localRevision: 1,
            _serverRevision: 0,
            _serverId: null,
        });
    }

    console.log('[Seeder] Bootstrap seeded:', things.length, 'things,',
        links.length, 'links,', demoObjects.length, 'demo objects');
}
