#!/bin/bash
now=$(date +"%Y_%m_%d")
echo "Backing up database to factology_$now.sql..."
docker exec factology-mysql sh -c "/usr/bin/mysqldump -u root --password=securerootpassword factology" > factology_$now.sql
echo "Backup complete!"
